### Create Reply
POST http://localhost:3000/api/replies
Content-Type: application/json

{
  "content": "testtttttt"
}


### Get All Replies
GET http://localhost:3000/api/replies

### Get Reply By Id
GET http://localhost:3000/api/replies/66c2f57f20348153c3cccc80



### Delete Reply
DELETE http://localhost:3000/api/replies/66b1817c992d8b14f1950c0f
